### ISSUE TITLE
OctetString conversion to String

### ISSUE THREAD

**Issue by vbob** [nospaceships/node-net-snmp#46]
I want to do a generic SNMP Subtree, but I am having problems with OctetString conversion: 
* MAC Adresses are decoded with `.toString('hex')`
* Text is decoded with `.toString('utf8')`

My code is the following: 
```TypeScript
this.connection.subtree(oid, (varbinds: Array<any>) => {
  varbinds.forEach(varbind => {
    if (snmp.isVarbindError(varbind))
      message.push({
        'oid': varbind.oid,
        'value': snmp.varbindError(varbind)
      })

    else {
      if (varbind['type'])
        varbind['type'] = snmp.ObjectType[varbind['type']]

      // How to make this statement generic?
      if (varbind['value'] instanceof Buffer)
        varbind['value'] = varbind['value'].toString("hex")

      message.push(varbind)
    }
  })
})
```

And my responses are: 
```TypeScript
[{
    oid: "1.3.6.1.2.1.2.2.1.2.2",
    type: "OctetString",
    value: "526564204861742c20496e63204465766963652030303031"
},
// [...]
{
    oid: "1.3.6.1.2.1.2.2.1.6.2",
    type: "OctetString",
    value: "82f8c67920e6"
}]
```

The expected ```snmpget``` responses are:

```
1.3.6.1.2.1.2.2.1.2.2 = STRING: Red Hat, Inc Device 0001
1.3.6.1.2.1.2.2.1.6.2 = STRING: 82:f8:c6:79:20:e6
```

How can I distinguish one from the other and create a generic subtree function with correct string conversion?

**Comment by stephenwvickers** [comment]
You will need to know the data type you are dealing with if they are both instances of `OctetString`.

If you can load the MIB file somehow, then you can use that to determine how to parse `OctetString` instances.
