### ISSUE TITLE
Example from README converted to Promise

### ISSUE THREAD

**Issue by phantompepper** [nospaceships/node-net-snmp#49]
Hi Stephen - this library is awesome! I am newish to Javascript and am curious on the smartest route to make your main example (session.get) from the README a Promise. I thought I would just ask you directly to see how you would go about it seeing how you build the thing and all. 

Thanks again!

**Comment by stephenwvickers** [comment]
Hi @phantompepper 

I've just seen this comment, for some reason I'd missed it until now.

I have to be honest, I am not a massive Promise fan, so I can't really advise.  You will likely need to write a shim over this API to replicate all it's functions.

Steve

**Comment by markabrahams** [comment]
@phantompepper - check out promisify - callbacks should be compatible with that structure.
