### ISSUE TITLE
Not receiving error on bad trap

### ISSUE THREAD

**Issue by Tr1gs** [nospaceships/node-net-snmp#50]
Hi there, I'm using v1.2.4 and even if I create a bogus session I'm not receiving errors either when I create the session, or send a trap.  My code:

```
        this.session = snmp.createSession('127.0.0.1', 'public', {'version': snmp.Version2c});
        this.session.on('error', (error: Error) => {
            console.error(error.toString());
            this.close();
        });
```
there's nothing on `127.0.0.1` (or any other IP I try), and I send a trap with

```
            new Promise<void>((resolve, reject) =>
                this.session.trap(trapOid, varbinds, (error: Error) => {
                    if (error) {
                        reject(error);
                    }

                    resolve();
                }))
```
`error` always returns `null`.  When I start my trap receiver everything works as expected but failure route is giving me no feedback.

Edit: looking at the code for session creation and trap (https://github.com/nospaceships/node-net-snmp/blob/master/index.js#L549 and https://github.com/nospaceships/node-net-snmp/blob/master/index.js#L1332) perhaps this is expected behaviour https://github.com/nospaceships/node-net-snmp/blob/master/index.js#L993.  I'm new to SNMP so I'm not familiar if you can expect an error if the destination is wrong.

**Comment by stephenwvickers** [comment]
Hi @Tr1gs 

This is expected.  The callback is called once the message is sent, it does not care if the message was received successfully by anything, SNMP traps require no response to be successful.

Steve
